import { Task } from './task.model';

export interface User {
  userId?: string; // Optional because it's auto-generated by Prisma
  userName: string;
  firstName?: string; // Optional based on your schema
  lastName?: string; // Optional based on your schema
  lastLogin?: Date;
  failedLoginAttempts?: number; // Has a default value in your schema
  role?: string; // Has a default value in your schema
  termsAcceptedAt?: Date;
  locale?: string;
  timeZone?: string;
  darkMode?: boolean; // Has a default value in your schema
  password: string; // This would be used for form input, not for storage
  createdAt?: Date; // Automatically set by Prisma
  tasks?: Task[]; // Optional one-to-many relationship with Task
}
